# Generated by Django 4.2.6 on 2024-01-12 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CabinetApp', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='title',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
