# Generated by Django 4.2.6 on 2023-10-16 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cabinet', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='url',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
