# Generated by Django 4.2.6 on 2023-10-15 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0002_user_is_verified_email_alter_user_is_teacher_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='posts/images'),
        ),
    ]
