# Generated by Django 4.2.6 on 2024-01-12 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProfileApp', '0002_alter_user_is_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='user_count',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
