# Generated by Django 4.2.6 on 2023-10-11 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0002_alter_user_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='users/images'),
        ),
    ]
