# Generated by Django 4.2.6 on 2024-01-12 11:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProfileApp', '0003_service_user_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='users',
            field=models.ManyToManyField(related_name='service_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
