# Generated by Django 4.2.6 on 2024-01-13 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProfileApp', '0007_alter_service_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='slug',
        ),
    ]
